import { defineGoogleAdsRule } from './googleAdsRuleSources';
import type { GoogleAdsRuleDefinition } from './googleAdsRuleTypes';

const category = 'CONVERSION' as const;
const readinessCategory = 'conversion-tracking' as const;

export const googleAdsConversionRules: GoogleAdsRuleDefinition[] = [
  defineGoogleAdsRule({
    id: 'platform-conversion-tracking',
    title: 'Conversion tracking đã xác nhận',
    source: 'PLATFORM_RULE',
    sourceId: 'GOOGLE_ADS_CONVERSIONS',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Tag/GTM/conversion action chưa xác nhận thì không launch bản copy chạy Ads.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: true,
    defaultStatus: 'unknown',
    missingEvidence: ['Google tag/GTM', 'Conversion action Primary/Secondary', 'Include in Conversions', 'Tag diagnostics'],
    evidenceKeys: ['conversionTrackingStatus', 'conversions'],
    recommendedActionVi: 'Test phone click, Zalo click, form submit, order completed hoặc thank-you event.',
    prohibitedActionVi: 'Không chọn Maximize Conversions khi tracking chưa xác nhận.',
    scoreImpact: 20,
  }),
  defineGoogleAdsRule({
    id: 'business-primary-goal',
    title: 'Mục tiêu chuyển đổi chính đã xác định',
    source: 'BUSINESS_GUARDRAIL',
    sourceId: 'BUSINESS_GUARDRAIL_INTERNAL',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Phải biết conversion chính là gọi/Zalo/form/order trước khi chọn bidding.',
    canBlockLaunch: true,
    unknownBlocksLaunch: true,
    defaultStatus: 'unknown',
    missingEvidence: ['Mục tiêu chính', 'Lead/order log nếu có'],
    evidenceKeys: ['conversionTrackingStatus', 'phoneCalls', 'zaloContacts', 'formSubmissions', 'orders'],
    recommendedActionVi: 'Map mục tiêu kinh doanh với conversion action.',
    prohibitedActionVi: 'Không dùng page view làm conversion chính nếu không phải mục tiêu kinh doanh.',
    scoreImpact: 20,
  }),
  ...([
    ['conversion-primary-action-selected', 'Primary conversion action đã chọn'],
    ['conversion-include-in-conversions-reviewed', 'Include in Conversions được kiểm tra'],
    ['conversion-counting-method-known', 'One/Every phù hợp mục tiêu'],
    ['conversion-phone-call-tracking-known', 'Phone call/click tracking rõ'],
    ['conversion-zalo-click-tracking-known', 'Zalo click tracking rõ'],
    ['conversion-form-submit-tracking-known', 'Form submit tracking rõ'],
    ['conversion-order-completed-tracking-known', 'Order completed tracking rõ'],
    ['conversion-no-duplicate-spike', 'Không có spike conversion trùng lặp'],
    ['conversion-no-tracking-stopped', 'Tracking không bị dừng sau giai đoạn chạy cũ'],
    ['conversion-lead-log-reconciled', 'Lead thật được đối chiếu với Ads conversions'],
  ] as const
  ).map(([id, title]) => defineGoogleAdsRule({
    id,
    title,
    source: id.includes('duplicate') || id.includes('stopped') ? 'PLATFORM_RULE' : 'BUSINESS_GUARDRAIL',
    sourceId: id.includes('duplicate') || id.includes('stopped') ? 'GOOGLE_ADS_API_CONVERSIONS' : 'BUSINESS_GUARDRAIL_INTERNAL',
    category,
    readinessCategory,
    severity: id.includes('duplicate') || id.includes('stopped') ? 'critical' : 'medium',
    summaryVi: 'Rule conversion bổ sung để không tối ưu theo dữ liệu sai hoặc thiếu.',
    stopRule: id.includes('duplicate') || id.includes('stopped'),
    canBlockLaunch: id.includes('duplicate') || id.includes('stopped'),
    defaultStatus: 'unknown',
    missingEvidence: ['Conversion settings', 'Lead log'],
    evidenceKeys: ['conversionTrackingStatus', 'conversions', 'phoneCalls', 'zaloContacts', 'formSubmissions', 'orders'],
    recommendedActionVi: 'Đối chiếu conversion settings với lead thật.',
    prohibitedActionVi: 'Không kết luận không có lead thật khi tracking chưa xác nhận.',
    scoreImpact: id.includes('duplicate') || id.includes('stopped') ? 20 : 3,
  })),
];
