import { defineGoogleAdsRule } from './googleAdsRuleSources';
import type { GoogleAdsRuleDefinition } from './googleAdsRuleTypes';

const category = 'ACCOUNT_SECURITY' as const;
const readinessCategory = 'account-policy' as const;

export const googleAdsAccountRules: GoogleAdsRuleDefinition[] = [
  defineGoogleAdsRule({
    id: 'official-account-status',
    title: 'Tài khoản đủ điều kiện phân phối',
    source: 'OFFICIAL_POLICY',
    sourceId: 'GOOGLE_ADS_ACCOUNT_STATUS',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Không lập kế hoạch chạy khi tài khoản bị đình chỉ, bị hủy hoặc trạng thái không rõ.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: true,
    defaultStatus: 'unknown',
    missingEvidence: ['Account status', 'Thông báo chính thức trong Google Ads hoặc email'],
    evidenceKeys: ['accountStatus', 'warningMessage', 'evidenceSource'],
    recommendedActionVi: 'Đối chiếu Account status/Policy manager/Billing trước khi copy campaign.',
    prohibitedActionVi: 'Không tạo tài khoản mới để né đình chỉ hoặc bỏ qua cảnh báo chính thức.',
    scoreImpact: 20,
  }),
  defineGoogleAdsRule({
    id: 'account-access-owner-confirmed',
    title: 'Quyền truy cập tài khoản được xác nhận',
    source: 'PLATFORM_RULE',
    sourceId: 'GOOGLE_ADS_ACCOUNT_STATUS',
    category,
    readinessCategory,
    severity: 'high',
    summaryVi: 'Cần biết nguồn bằng chứng và quyền đọc trạng thái để tránh đoán.',
    canBlockLaunch: false,
    unknownBlocksLaunch: false,
    defaultStatus: 'unknown',
    missingEvidence: ['Nguồn bằng chứng', 'Vai trò người kiểm tra tài khoản'],
    evidenceKeys: ['evidenceSource', 'notes'],
    recommendedActionVi: 'Ghi nguồn ảnh chụp/trạng thái từ tài khoản Google Ads.',
    prohibitedActionVi: 'Không kết luận tài khoản ổn nếu chỉ có ghi chú miệng.',
    scoreImpact: 4,
  }),
  defineGoogleAdsRule({
    id: 'account-no-circumvention-risk',
    title: 'Không có dấu hiệu né tránh hệ thống',
    source: 'OFFICIAL_POLICY',
    sourceId: 'AD_POLICY_MISREPRESENTATION',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Nếu ghi chú/cảnh báo nói về né tránh chính sách thì phải dừng.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: false,
    defaultStatus: 'not_applicable',
    missingEvidence: ['Policy details nếu có cảnh báo'],
    evidenceKeys: ['warningMessage', 'policyStatus', 'notes'],
    recommendedActionVi: 'Xử lý đúng lý do Google nêu trước khi tiếp tục.',
    prohibitedActionVi: 'Không đổi domain/tài khoản để lách xét duyệt.',
    scoreImpact: 20,
  }),
  defineGoogleAdsRule({
    id: 'account-no-suspected-compromise',
    title: 'Không có dấu hiệu tài khoản/website bị xâm nhập',
    source: 'PLATFORM_RULE',
    sourceId: 'GOOGLE_ADS_ACCOUNT_STATUS',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Nghi ngờ compromise/malware phải xử lý bảo mật trước khi chạy.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: false,
    defaultStatus: 'not_applicable',
    missingEvidence: ['Cảnh báo bảo mật nếu có'],
    evidenceKeys: ['warningMessage', 'notes'],
    recommendedActionVi: 'Kiểm tra cảnh báo bảo mật, quyền truy cập và thay đổi bất thường.',
    prohibitedActionVi: 'Không bật quảng cáo khi chưa xử lý cảnh báo compromise.',
    scoreImpact: 20,
  }),
  defineGoogleAdsRule({
    id: 'account-no-mass-disapproval',
    title: 'Không có từ chối quảng cáo hàng loạt chưa xử lý',
    source: 'OFFICIAL_POLICY',
    sourceId: 'AD_POLICY_MISREPRESENTATION',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Mass disapproval là tín hiệu dừng, không chỉ là cảnh báo nhẹ.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: false,
    defaultStatus: 'not_applicable',
    missingEvidence: ['Policy manager', 'Danh sách ads bị từ chối'],
    evidenceKeys: ['accountStatus', 'policyStatus', 'warningMessage'],
    recommendedActionVi: 'Sửa nguyên nhân từ chối trước khi tạo bản copy mới.',
    prohibitedActionVi: 'Không copy lại mẫu quảng cáo bị từ chối sang campaign mới.',
    scoreImpact: 20,
  }),
];
