import { defineGoogleAdsRule } from './googleAdsRuleSources';
import type { GoogleAdsRuleDefinition } from './googleAdsRuleTypes';

export const googleAdsPolicyRules: GoogleAdsRuleDefinition[] = [
  defineGoogleAdsRule({
    id: 'official-policy-warning',
    title: 'Không còn policy warning/disapproval chưa xử lý',
    source: 'OFFICIAL_POLICY',
    sourceId: 'AD_POLICY_MISREPRESENTATION',
    category: 'POLICY_MISREPRESENTATION',
    readinessCategory: 'account-policy',
    severity: 'critical',
    summaryVi: 'Cảnh báo policy, limited hoặc disapproved phải được xử lý trước khi launch.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: true,
    defaultStatus: 'unknown',
    missingEvidence: ['Policy manager', 'Lý do từ chối nguyên văn', 'Final URL liên quan'],
    evidenceKeys: ['policyStatus', 'warningMessage', 'accountStatus'],
    recommendedActionVi: 'Sửa nội dung/landing theo lý do Google nêu, chỉ appeal khi đã khắc phục.',
    prohibitedActionVi: 'Không tự gửi appeal hoặc khẳng định đã khắc phục khi chưa có bằng chứng.',
    scoreImpact: 20,
  }),
  ...([
    ['policy-truthful-business-identity', 'Danh tính doanh nghiệp không gây hiểu nhầm', 'AD_POLICY_MISREPRESENTATION', 'POLICY_MISREPRESENTATION'],
    ['policy-no-false-official-claims', 'Không claim chính hãng/số 1/rẻ nhất nếu chưa xác nhận', 'AD_POLICY_MISREPRESENTATION', 'POLICY_MISREPRESENTATION'],
    ['policy-price-promotion-evidence', 'Giá/khuyến mãi có bằng chứng', 'AD_POLICY_MISREPRESENTATION', 'POLICY_MISREPRESENTATION'],
    ['policy-no-counterfeit-risk', 'Không có rủi ro hàng giả/hàng nhái', 'AD_POLICY_PROHIBITED_RESTRICTED', 'RESTRICTED_PROHIBITED_CONTENT'],
    ['policy-no-prohibited-content', 'Không quảng cáo nội dung bị cấm', 'AD_POLICY_PROHIBITED_RESTRICTED', 'RESTRICTED_PROHIBITED_CONTENT'],
    ['policy-restricted-content-not-applicable', 'Nội thất không thuộc nhóm hạn chế đặc thù', 'AD_POLICY_PROHIBITED_RESTRICTED', 'RESTRICTED_PROHIBITED_CONTENT'],
    ['policy-editorial-clarity', 'Nội dung rõ ràng, không gây nhầm lẫn', 'AD_POLICY_MISREPRESENTATION', 'POLICY_MISREPRESENTATION'],
    ['policy-no-before-after-sensitive-claims', 'Không dùng claim nhạy cảm không phù hợp ngành', 'AD_POLICY_PROHIBITED_RESTRICTED', 'RESTRICTED_PROHIBITED_CONTENT'],
    ['policy-local-service-coverage-truthful', 'Khu vực phục vụ đúng thực tế', 'AD_POLICY_MISREPRESENTATION', 'POLICY_MISREPRESENTATION'],
    ['policy-review-rating-evidence', 'Review/rating nếu dùng phải có nguồn', 'AD_POLICY_MISREPRESENTATION', 'POLICY_MISREPRESENTATION'],
    ['policy-contact-info-consistent', 'Thông tin liên hệ nhất quán với landing page', 'AD_POLICY_MISREPRESENTATION', 'POLICY_MISREPRESENTATION'],
    ['policy-ad-appeal-not-auto', 'Không tự appeal khi chưa đủ bằng chứng', 'AD_POLICY_MISREPRESENTATION', 'POLICY_MISREPRESENTATION'],
  ] as const
  ).map(([id, title, sourceId, ruleCategory]) => defineGoogleAdsRule({
    id,
    title,
    source: 'OFFICIAL_POLICY',
    sourceId,
    category: ruleCategory as GoogleAdsRuleDefinition['category'],
    readinessCategory: 'account-policy',
    severity: 'high',
    summaryVi: 'Rule chính sách chính thức: thiếu bằng chứng thì unknown, không tự kết luận pass.',
    canBlockLaunch: id.includes('counterfeit') || id.includes('prohibited'),
    unknownBlocksLaunch: false,
    defaultStatus: id.includes('restricted-content-not-applicable') ? 'not_applicable' : 'unknown',
    missingEvidence: ['Policy details', 'Nội dung ad/landing page liên quan'],
    evidenceKeys: ['policyStatus', 'warningMessage', 'notes'],
    recommendedActionVi: 'Đối chiếu nội dung với Policy manager và sửa theo lý do cụ thể.',
    prohibitedActionVi: 'Không suy diễn vi phạm nếu URL chưa xác minh hoặc nguồn policy chưa rõ.',
    scoreImpact: 3,
  })),
];
