import { defineGoogleAdsRule } from './googleAdsRuleSources';
import type { GoogleAdsRuleDefinition } from './googleAdsRuleTypes';

const category = 'BILLING_VERIFICATION' as const;
const readinessCategory = 'billing-verification' as const;

export const googleAdsBillingRules: GoogleAdsRuleDefinition[] = [
  defineGoogleAdsRule({
    id: 'platform-billing',
    title: 'Billing/payment không có lỗi chặn phân phối',
    source: 'PLATFORM_RULE',
    sourceId: 'GOOGLE_ADS_BILLING',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Lỗi thanh toán, nợ hoặc phương thức bị từ chối phải chặn launch.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: true,
    defaultStatus: 'unknown',
    missingEvidence: ['Billing summary', 'Payment methods', 'Khoản nợ nếu có'],
    evidenceKeys: ['billingStatus', 'accountStatus'],
    recommendedActionVi: 'Cập nhật phương thức thanh toán hợp lệ trong Google Ads.',
    prohibitedActionVi: 'Không lưu số thẻ, OTP, token hoặc mật khẩu trong dashboard.',
    scoreImpact: 10,
  }),
  defineGoogleAdsRule({
    id: 'official-advertiser-verification',
    title: 'Advertiser verification không chặn phân phối',
    source: 'OFFICIAL_POLICY',
    sourceId: 'GOOGLE_ADS_ADVERTISER_VERIFICATION',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Yêu cầu xác minh nhà quảng cáo chưa hoàn tất có thể chặn hoặc giới hạn launch.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: true,
    defaultStatus: 'unknown',
    missingEvidence: ['Advertiser verification status', 'Thông báo hạn xác minh nếu có'],
    evidenceKeys: ['advertiserVerificationStatus', 'accountStatus'],
    recommendedActionVi: 'Hoàn tất xác minh theo yêu cầu trong Google Ads.',
    prohibitedActionVi: 'Không nhập/lưu giấy tờ nhạy cảm trong dashboard nếu không có luồng bảo mật riêng.',
    scoreImpact: 10,
  }),
  defineGoogleAdsRule({
    id: 'billing-no-spend-cap-overrun',
    title: 'Không vượt giới hạn chi tiêu người dùng nhập',
    source: 'BUSINESS_GUARDRAIL',
    sourceId: 'BUSINESS_GUARDRAIL_INTERNAL',
    category,
    readinessCategory,
    severity: 'critical',
    summaryVi: 'Khi chi tiêu thực tế hoặc budget đề xuất vượt cap người dùng, phải dừng.',
    stopRule: true,
    canBlockLaunch: true,
    unknownBlocksLaunch: false,
    defaultStatus: 'not_applicable',
    missingEvidence: ['Daily budget cap', 'Actual spend'],
    evidenceKeys: ['dailyBudget', 'actualSpend', 'userDailyBudgetCap'],
    recommendedActionVi: 'Giữ budget dưới giới hạn đã nhập.',
    prohibitedActionVi: 'Không tăng ngân sách để che lỗi tracking/policy/landing page.',
    scoreImpact: 10,
  }),
  ...([
    ['billing-tax-profile-known', 'Đã xác nhận hồ sơ thuế thanh toán'],
    ['billing-payment-method-current', 'Phương thức thanh toán còn hiệu lực'],
    ['billing-no-account-balance-due', 'Không có khoản dư nợ chặn phân phối'],
    ['billing-currency-timezone-reviewed', 'Đã kiểm tra đơn vị tiền tệ và múi giờ'],
  ] as const).map(([id, title]) => defineGoogleAdsRule({
    id,
    title,
    source: 'PLATFORM_RULE',
    sourceId: 'GOOGLE_ADS_BILLING',
    category,
    readinessCategory,
    severity: 'medium',
    summaryVi: 'Kiểm tra billing phụ trợ trước launch; thiếu bằng chứng chỉ tạo cảnh báo.',
    canBlockLaunch: false,
    defaultStatus: 'unknown',
    missingEvidence: ['Billing settings'],
    evidenceKeys: ['billingStatus'],
    recommendedActionVi: 'Kiểm tra Billing > Settings/Summary.',
    prohibitedActionVi: 'Không lưu dữ liệu thanh toán nhạy cảm.',
    scoreImpact: 2,
  })),
];
